### PR TITLE
Splitting subjects across separate Primary and Secondary routes

### PR DESCRIPTION
**Pull request by frankieroberto**
This builds upon https://github.com/DFE-Digital/find-teacher-training-prototype/pull/30 which dropped the accordion in favour of a list of checkboxes, for accessibility and usability reasons.

As a further enhancement, this PR makes the list of checkboxes more usable by first asking whether someone wants to teach Primary or Secondary aged children. This is based on the assumption that few teachers are unsure about this at this stage, and that the likelihood of wanting to search for Primary AND Secondary courses at the same time is low.

For Primary, a follow-up guard question is used to introduce the notion of the specialist subject, which is then followed by a list of specialist subjects if the candidate is interested.

For Secondary, the list of subjects is presented as a single alphabetical list (including all the languages subjects) to aid scanning.

The results page needs some further thought, but an initial idea is to remove the age group / subjects from the Filter box altogether, in order to make the other filters (which the candidate hasn't yet seen) more visible, and all behave in the same way.

Instead, the age group and subject(s) are shown at the top of the page in place of the static caption, with a "Change" link. This takes you back to the homepage where you can go through the flow again - but your previous answers are remembered.

TODO:

* [x] consider how SEND specialist courses should be treated. As a separate filter, or part of the initial subject flow?
* [x] work out what happens when you click "Change" for the age group and subjects
* [ ] is the content about scholarships and bursaries in the right place (subject hint text)?
* [x] would it be better to have the list of Primary or Secondary subjects as checkbox filters (optionally with search)?
* [x] should the Find homepage also contain a list of popular course types (like Primary, English, etc) which could link direct to results?

## Screenshots

screenshot-localhost_3010-2021 05 28-17_22_23

screenshot-localhost_3010-2021 05 28-17_22_44

screenshot-localhost_3010-2021 05 28-17_23_07

screenshot-localhost_3010-2021 05 31-20_04_11

screenshot-localhost_3010-2021 05 28-17_24_38

### CODE REVIEW

**Comment by B-Bonner** [comment]
The content's fine and I think it's really easy to use. 

I noticed that when you select a number of areas, it becomes difficult to read all the bold text at the top of the page. I don't know if we can arrange the list differently, or not use bold: 
Screenshot 2021-06-22 at 08 22 28


Perhaps a 'Select all boroughs' tick box might be useful here. I don't know how else you'd choose the whole of London without manually ticking every box:
Screenshot 2021-06-22 at 08 24 47


When you select 'All courses in England', it doesn't show this selection at the top, instead, it shows your previous selection. Even though its updated the search results beneath:

Screenshot 2021-06-22 at 08 28 27

**Comment by paulrobertlloyd** [comment]
* I wonder if splitting the primary question into specialist/non-specialist is going a bit too far. But worth testing!
* I think the selected location/subject should probably come after the page heading. I wonder also is there’s a better way of displaying these?

As to the London Boroughs, I agree, all the bold text is a problem. But I’m unsure if this is something we’d want to retain – really depends on what we do next with locations. (This prototype currently shows a design where you could search by area, and if you picked London, could then narrow down by borough)

**Comment by frankieroberto** [comment]
@paulrobertlloyd my thinking with the Primary courses was that it seemed the "specialist" subject needed a bit of explaining anyway, so may as well turn it into an explicit question. I'm also assuming that most people just want to see Primary courses, so this saves them having to read through the subject list. Will be interesting to see how it tests though.

Open to ideas on how we display the currently selected course type and location (and the change link). I put it before the h1 as a kind-of replacement for existing static caption ("Teacher training courses").

One option could be to merge the text in with the h1 itself, so instead of "13 courses found" it'd say "13 Primary courses in Birmingham found". But that could get quite long if you select lots of subjects (although I suspect that's rare?)

Also need to work out where SEND-specialist courses go. Should that be part of initial flow, or a checkbox filter on the left? 🤔

**Comment by frankieroberto** [comment]
I've added "Special educational needs and disability (SEND)" alongside the Primary and Secondary subjects for now, as I think it’s closest to a specialist subject, particularly for Primary, where there is only [a single course](https://www.find-postgraduate-teacher-training.service.gov.uk/course/W80/3DP6) which is SEND-specialist AND has a different specialist subject.

**Comment by B-Bonner** [comment]
I just checked SEND against the gov.uk style guide and its written differently (see below).

Screenshot 2021-07-05 at 08 36 42

 Do we write it as 'special educational needs and disability (SEND)' in all the becoming a teacher content (across GIT, Apply, etc)?

**Pull request merged**
