### PR TITLE
Add link to Get Into Teaching on course details page

### PR DESCRIPTION
**Pull request by paulrobertlloyd**
Add links to Get Into Teaching on [course details page](https://find-prototy-git-links-wuogvtw.herokuapp.com/course/153/2N4C#advice).

### CODE REVIEW

**Comment by paulrobertlloyd** [comment]
[Add GiT links to Apply/Find](https://trello.com/c/EC0lo4u6/3728-add-git-links-to-apply-find)

**Comment by B-Bonner** [comment]
Thanks, that's great. I just noticed that the new link is in purple even before you've clicked on it. I don't know if something needs fixing there?

**Comment by paulrobertlloyd** [comment]
It’ll be purple if you’ve visited that link before 😃

**Comment by B-Bonner** [comment]
Yeah, they were purple before I visited them.

**Pull request merged**
